# Generated by Django 4.0.4 on 2022-08-04 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserStudyPS',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('PS', models.CharField(max_length=30)),
                ('post', models.ForeignKey(db_column='post_ps', on_delete=django.db.models.deletion.CASCADE, related_name='PS', to='profiles.userstudy')),
            ],
        ),
        migrations.CreateModel(
            name='UserStudyCS',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('CS', models.CharField(max_length=30)),
                ('post', models.ForeignKey(db_column='post_cs', on_delete=django.db.models.deletion.CASCADE, related_name='CS', to='profiles.userstudy')),
            ],
        ),
        migrations.CreateModel(
            name='UserSkillsLan',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=30)),
                ('post', models.ForeignKey(db_column='post_anguage', on_delete=django.db.models.deletion.CASCADE, related_name='post_anguage', to='profiles.userskills')),
            ],
        ),
        migrations.CreateModel(
            name='UserSkillsFram',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('framework', models.CharField(max_length=30)),
                ('post', models.ForeignKey(db_column='post_framework', on_delete=django.db.models.deletion.CASCADE, related_name='post_framework', to='profiles.userskills')),
            ],
        ),
        migrations.CreateModel(
            name='UserOngoing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ongoing', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hashtag', models.CharField(max_length=100, null=True)),
                ('belongs', models.CharField(max_length=30)),
                ('major', models.CharField(max_length=30)),
                ('position', models.CharField(max_length=30)),
                ('subposition', models.CharField(max_length=30, null=True)),
                ('introduction', models.CharField(max_length=200, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserCert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('certification', models.CharField(max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserCareer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('career_at', models.CharField(max_length=30)),
                ('career_who', models.CharField(max_length=30)),
                ('career_when', models.CharField(max_length=30)),
                ('career_what', models.CharField(max_length=100)),
                ('career_achieve', models.CharField(max_length=100)),
                ('career_skills', models.CharField(max_length=100)),
                ('email', models.ForeignKey(db_column='user_email', on_delete=django.db.models.deletion.CASCADE, related_name='user_email', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
